/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VCellId_v1CellIdPath.java
 *
 * Created on Sep 12, 2011, 2:04:00 AM
 */

package vcellid_v1;

import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import org.jdesktop.application.Action;

/**
 *
 * @author alejandropetit
 */
public class VCellId_v1CellIdPath extends javax.swing.JDialog {

    /** Creates new form VCellId_v1CellIdPath */
    public VCellId_v1CellIdPath(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cellIdChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(vcellid_v1.VCellId_v1App.class).getContext().getResourceMap(VCellId_v1CellIdPath.class);
        cellIdChooser.setDialogTitle(resourceMap.getString("cellIdChooser.dialogTitle")); // NOI18N
        cellIdChooser.setFileFilter(new ExeFilter());
        cellIdChooser.setName("cellIdChooser"); // NOI18N
        cellIdChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellIdChooserActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(cellIdChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(cellIdChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cellIdChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellIdChooserActionPerformed
       JFileChooser theFileChooser = (JFileChooser) evt.getSource();
       String command = evt.getActionCommand();

        if (command.equals(JFileChooser.APPROVE_SELECTION)) {
            File file = theFileChooser.getSelectedFile();
            //TODO: obtuve el archivo, vemos que hacer con el.
        }else{
         dispose();
        }
    }//GEN-LAST:event_cellIdChooserActionPerformed

    class ExeFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".exe");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Executable documents (*.exe)";
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VCellId_v1CellIdPath dialog = new VCellId_v1CellIdPath(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser cellIdChooser;
    // End of variables declaration//GEN-END:variables

}
